### ISSUE TITLE
ENH: Crafted wheels with separate customizations

### ISSUE THREAD

**Issue by anchillabc** [bananarama92/MBS#25]
I don't know if this is technically possible, but it would be very nice to be able to switch between different wheels with completely different content.

This might work by assigning a name to each wheel customization page which must be found in the name (or description) of the crafted wheel which is equipped.
This would allow us to switch between wheels with longer or shorter timers or completely different content.
This suggestion makes more sense in conjunction with my other suggestion of additional custom option pages for the wheel.

**Comment by anchillabc** [comment]
That is not a compromise, this is exactly what I had in mind :) When writing the proposal, this is why I looked up the names of the pages specifically - no need to duplicate items when you use crafted wheel name / description to reference customization (checkboxes) page name field only.

**Comment by bananarama92** [comment]
Implemented as of https://github.com/bananarama92/MBS/pull/79
