### ISSUE TITLE
Loading over FUSAM leads to version mismatch

### ISSUE THREAD

**Issue by anchillabc** [bananarama92/MBS#36]
I know this should probably be dealth with by FUSAM development, but since this causes a mismatch between wheel providers and spinners, it's also an MBS issue at the same time. The latest version often does not get loaded by everyone.

**Comment by bananarama92** [comment]
I just regenerated the v0.6.23 release artifacts on github pages as they disappeared (again...), can you (force) refresh your browser and try again?
