### ISSUE TITLE
GUI is acting up when saving custom outfit

### ISSUE THREAD

**Issue by M3rcuz1o** [bananarama92/MBS#4]
When I add an outfit and name it and save it, after I leave the menu, the controls of the WoF are gone. I have to exit WoF and re-enter, and then it's there. It's working fine, but it's a visual glitch that might repell users that are not used to broken interfaces. :-)

**Comment by M3rcuz1o** [comment]
![image](https://user-images.githubusercontent.com/124259429/216555334-f3e89aa5-f3f7-4e62-b272-b73217c9899d.png)

**Comment by bananarama92** [comment]
Yeah, I've seen the issue before (ever since the initial introduction of the wheel in fact, predating MBS...). It's a problem inside BC itself with loading one of its wheel of fortune-related .csv files; not sure what's causing it though.

**Comment by dragon011** [comment]
but you can fix it Self for Close and Open it than works it fine. This is about the Release broken a bit

**Comment by bananarama92** [comment]
Just accidentally stumbled upon a fix while preparing a new release.
The issue has been fixed as of the latest [v0.5.2 release](https://github.com/bananarama92/MBS/releases/tag/v0.5.2).
