### ISSUE TITLE
Extra crafting pages keep wiping out

### ISSUE THREAD

**Issue by Mahosys** [bananarama92/MBS#49]
Hi,

I have a problem for something like a month now, the extra pages of MBS keep resetting at random period.
I don't know how to reproduce it tho, it seems pretty random, sometime it takes few days to reset, sometime few weeks.

My first 4 vanilla page are good and never reset, but the 4 extra pages wipes out, leaving them all blank.

if it can helps, here some random infos :

MBS is installed using tampermonkey.
My vanilla crafting pages are kinda full (72/80 slots used).
Even with only 1 craft added to the extra pages it can wipe out.

**Comment by anchillabc** [comment]
It looks like your profile is already using the maximum allotted server side storage, or very close to it. 
Consider cutting down on the use of the FBC wardrobe if you're using it as that consumes a lot of space as well.
If using LSCG and spells, see if you can replace outfit / polymorph definitions with things which already exist in your wheel.
Basically, you're guaranteed the use of the first four pages as storage and the next 4 pages count against your quota which is shared by all addons.

**Comment by Mahosys** [comment]
I'm starting to run low on outfit slots too yeah ><
But removing outfits ? I can override an outfit with another one, but not really erase it.

Is there a way to know how much storage i'm using, or how much is left ?

Thanks for the answer.

**Comment by anchillabc** [comment]
I suggest asking on Discord, in the errors channel, I am not qualified to give you this advice, I ended up deleting that data via JS after logging in with addons disabled, you could also reset FBC data if you don't mind, but you will lose all outfits past the first 2 pages.
For me, deleting that was enough.

**Comment by bananarama92** [comment]
Have yet to find the root of the actual issue, though the v1.1.1 release (xref https://github.com/bananarama92/MBS/discussions/56) contains new diagnostic information related to crafted item problems. Hopefully this will some useful info in the future.
