### ISSUE TITLE
MBS fails to load after unhandled exception during settings initialisation

### ISSUE THREAD

**Issue by Drey230** [bananarama92/MBS#5]
I used the addon successfully one evening, however soon after it failed to load and continues to do so. After reading the console it seems it is unable to read something during initialisation.

> Uncaught (in promise) ReferenceError: Cannot access 'te' before initialization
    at a (settings.ts:68:50)
    at settings.ts:133:5

settings.ts:68
`Player.MBSSettings = <MBSSettings>{ Version: MBS_VERSION };`

Beyond this- I am unsure why it is throwing an exception. I am not familiar enough with Typescript or BC addons to even make an educated guess.

**Comment by bananarama92** [comment]
Odd, I'm struggling to see right now how a constant like `MBS_VERSION` could be initialized at this point.
Could you, for the sake of completeness, show me the entire console output up to the point of crashing?

**Comment by Drey230** [comment]
I have diagnosed the issue as an conflict with an old cheat addon for Bondage College [https://github.com/tasadar2/Bondage-College-Cheats](url). Both addons load if enabled on Tampermonkey. I am unsure why it affects MBS and not other common BC mods.

**Comment by Drey230** [comment]
My previous comment is incorrect. MBS does still work when it is the only addon being used. It also seems to load correctly when BCX is used as well. However when I add FBC to the mix- it _sometimes_ works for the first time in a tab, but fails every time afterwards when the page is reloaded. I am using no other addons for BC.

For the sake of completeness the entire console log.

> DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

> DevTools failed to load source map: Could not load content for https://www.bondageprojects.elementfx.com/R88/BondageClub/Screens/MiniGame/KinkyDungeon/pixi-legacy.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

> DevTools failed to load source map: Could not load content for chrome-extension://gannpgaobkkhmpomoijebaigcapoeebl/bundle.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

> Appearance.js:504 Uncaught TypeError: Cannot read properties of undefined (reading 'VisualSettings')
>     at CharacterAppearanceSetHeightModifiers (Appearance.js:504:25)
>     at CharacterLoadCanvas (Character.js:1076:2)
>     at CharacterReset (Character.js:422:2)
>     at CharacterLoadSimple (Character.js:627:12)
>     at equipper.ts:27:18
>     at index.ts:15:6
> CharacterAppearanceSetHeightModifiers @ Appearance.js:504
> CharacterLoadCanvas @ Character.js:1076
> CharacterReset @ Character.js:422
> CharacterLoadSimple @ Character.js:627
> (anonymous) @ equipper.ts:27
> (anonymous) @ index.ts:15

> index.ts:20 BCX Ready!

> (index):313 Version: R88, Server: https://bondage-club-server.herokuapp.com/

> Server.js:149 Connected to the Bondage Club Server.

> Server.js:153 
> WARNING! Console scripts can break your account or steal your data. Only run scripts if you know what you're doing and you trust the source. See https://gitgud.io/BondageProjects/Bondage-College/-/wikis/Player-Safety#scripts-browser-extensions to learn more about script safety. 

> main.ts:101 BCX loaded! Version: 0.9.3-8676a336

> settings.ts:68 Uncaught (in promise) ReferenceError: Cannot access 'te' before initialization
>     at a (settings.ts:68:50)
>     at settings.ts:133:5

I didn't notice the other exception was also MBS. Oops.

**Comment by bananarama92** [comment]
> ``` js
> Appearance.js:504 Uncaught TypeError: Cannot read properties of undefined (reading 'VisualSettings')
> at CharacterAppearanceSetHeightModifiers (Appearance.js:504:25)
> at CharacterLoadCanvas (Character.js:1076:2)
> at CharacterReset (Character.js:422:2)
> at CharacterLoadSimple (Character.js:627:12)
> at equipper.ts:27:18
> at index.ts:15:6
> CharacterAppearanceSetHeightModifiers @ Appearance.js:504
> CharacterLoadCanvas @ Character.js:1076
> CharacterReset @ Character.js:422
> CharacterLoadSimple @ Character.js:627
> (anonymous) @ equipper.ts:27
> (anonymous) @ index.ts:15
> ```
Ok, looking at this I think I know what's going on; I'll create a patch a bit later today.

**Comment by bananarama92** [comment]
Ok, should be fixed as of https://github.com/bananarama92/MBS/commit/a32fcc8c463c18d18b3de33bb00ff80bbcb46b56 which is included in the v0.4.0 release just now.
