### ISSUE TITLE
ENH: Frequency adjustments

### ISSUE THREAD

**Issue by anchillabc** [bananarama92/MBS#52]
This is an enhancement proposal.
Goal: Provide a way to adjust the number of times an outfit or command appears on the wheel when spun, without having to store the same outfit or command multiple times.

I don't know if this is possible at all with the underlying wheel infrastructure from BC itself... but it's an idea that might be worth implementing...

**Comment by bananarama92** [comment]
And implemented as of v1.1.0 (xref https://github.com/bananarama92/MBS/discussions/54): it's now possible to specify a weight in the [1,9] interval for all custom item sets and commands. Note that it's not possible to do so on a lock-type-by-lock-type basis, which would be a feature that is currently not planned.
