### ISSUE TITLE
MBS has stopped applying stored codes correctly

### ISSUE THREAD

**Issue by anchillabc** [bananarama92/MBS#64]
Oddly, the MBS wheel is completely broken.
While codes stored are functionally identical to previous backups and item configurations are still present when the code is uncompressed, these are not applied at all.
VR glasses with setting are just unconfigured, tentacles apply without a pose and all items simply get put on in their default setting.

**Comment by bananarama92** [comment]
Fixed as of https://github.com/bananarama92/MBS/discussions/66.
